domain_size: [100, 100]
n_timesteps: 10000
export_frequency: 100
velocity_set: "D2Q9" # "D3Q19", "D3Q27"
tau: 0.65
boundary_conditions:
  x_minus:
    bc_type: "Bounce-Back"
  x_plus:
    bc_type: "Bounce-Back"
  y_minus:
    bc_type: "Zhou-He"
    u: 0.05
  y_plus:
    bc_type: "Bounce-Back"
